// Generated by sdkgen go-cli target.
package main

import (
	"fmt"
	"strings"

	eng "github.com/boru-lang/boru/eng/go"
	sdk "github.com/voxgig-sdk/zoom-sdk/go"
)

func registerSDKWords(r *eng.Registry, client *sdk.ZoomSDK) {
	for _, op := range []string{"list", "load", "update"} {
		op := op
		single := eng.Signature{
			Args:      []*eng.Type{eng.TAtom},
			QuoteArgs: map[int]bool{0: true},
			Impl: eng.Go(func(args []eng.Value, _ map[string]eng.Value, _ []eng.Value, _ *eng.Registry) ([]eng.Value, error) {
				return runOp(client, op, nil, args[0])
			}),
			Returns:    []*eng.Type{eng.TAny},
			BarrierPos: eng.BarrierAllForward,
		}
		dual := eng.Signature{
			Args:      []*eng.Type{eng.TAny, eng.TAtom},
			QuoteArgs: map[int]bool{1: true},
			Impl: eng.Go(func(args []eng.Value, _ map[string]eng.Value, _ []eng.Value, _ *eng.Registry) ([]eng.Value, error) {
				q := args[0]
				return runOp(client, op, &q, args[1])
			}),
			Returns:    []*eng.Type{eng.TAny},
			BarrierPos: eng.BarrierAllForward,
		}
		r.RegisterNativeFunc(eng.NativeFunc{
			Name:       op,
			Signatures: []eng.Signature{single, dual},
		})
	}
}

func runOp(client *sdk.ZoomSDK, op string, query *eng.Value, entityAtom eng.Value) ([]eng.Value, error) {
	entityName, err := eng.AsAtom(entityAtom)
	if err != nil {
		return nil, fmt.Errorf("%s: entity argument is not an atom: %w", op, err)
	}
	ent, err := entityFor(client, entityName)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", op, err)
	}

	var arg map[string]any
	if query != nil {
		arg, err = queryToMap(*query)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", op, err)
		}
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(arg, nil)
	case "load":
		result, err = ent.Load(arg, nil)
	case "update":
		result, err = ent.Update(arg, nil)
	default:
		return nil, fmt.Errorf("unknown op %q", op)
	}
	if err != nil {
		return nil, err
	}
	return []eng.Value{eng.FromNative(extractData(result))}, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.ZoomSDK, name string) (sdk.ZoomEntity, error) {
	switch strings.ToLower(name) {
	case "account":
		return client.Account(nil), nil
	case "account_plan":
		return client.AccountPlan(nil), nil
	case "account_setting":
		return client.AccountSetting(nil), nil
	case "billing":
		return client.Billing(nil), nil
	case "cloud_recording":
		return client.CloudRecording(nil), nil
	case "dashboard":
		return client.Dashboard(nil), nil
	case "device":
		return client.Device(nil), nil
	case "domains_list":
		return client.DomainsList(nil), nil
	case "group":
		return client.Group(nil), nil
	case "group_member_list":
		return client.GroupMemberList(nil), nil
	case "im_chat":
		return client.ImChat(nil), nil
	case "im_group":
		return client.ImGroup(nil), nil
	case "im_group_list":
		return client.ImGroupList(nil), nil
	case "meeting":
		return client.Meeting(nil), nil
	case "meeting_instance":
		return client.MeetingInstance(nil), nil
	case "meeting_invitation":
		return client.MeetingInvitation(nil), nil
	case "meeting_registrant_list":
		return client.MeetingRegistrantList(nil), nil
	case "pac":
		return client.Pac(nil), nil
	case "poll":
		return client.Poll(nil), nil
	case "qos":
		return client.Qos(nil), nil
	case "recording":
		return client.Recording(nil), nil
	case "recording_setting":
		return client.RecordingSetting(nil), nil
	case "report":
		return client.Report(nil), nil
	case "tracking_field":
		return client.TrackingField(nil), nil
	case "tsp":
		return client.Tsp(nil), nil
	case "user":
		return client.User(nil), nil
	case "user_assistants_list":
		return client.UserAssistantsList(nil), nil
	case "user_permission":
		return client.UserPermission(nil), nil
	case "user_schedulers_list":
		return client.UserSchedulersList(nil), nil
	case "user_setting":
		return client.UserSetting(nil), nil
	case "webhook":
		return client.Webhook(nil), nil
	case "webinar":
		return client.Webinar(nil), nil
	case "webinar_instance":
		return client.WebinarInstance(nil), nil
	case "webinar_panelist_list":
		return client.WebinarPanelistList(nil), nil
	case "webinar_registrant_list":
		return client.WebinarRegistrantList(nil), nil
	case "zoom_room_list":
		return client.ZoomRoomList(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// queryToMap converts a boru Value (Map or Scalar) into the
// `map[string]any` shape the SDK expects. Maps are unwrapped via
// eng.ToNative. Scalars are wrapped as {"id": <value>} so the
// shorthand `load 1 book` becomes `load {id:1} book`.
func queryToMap(v eng.Value) (map[string]any, error) {
	if v.Parent.ConformsTo(eng.TMap) {
		m, ok := eng.ToNative(v).(map[string]any)
		if !ok {
			return nil, fmt.Errorf("query map could not be unwrapped")
		}
		return m, nil
	}
	if v.Parent.ConformsTo(eng.TScalar) {
		return map[string]any{"id": eng.ToNative(v)}, nil
	}
	return nil, fmt.Errorf("query must be a Map or Scalar, got %s", v.Parent)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with the underlying record via .Data().
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}
